name: Frontend Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env
        run: |
          touch .env.prod
          echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" >> .env.prod
          echo "VITE_SOCK_URL=${{ secrets.VITE_SOCK_URL }}" >> .env.prod
          echo "VITE_CLIENT_PORT=${{ secrets.VITE_CLIENT_PORT }}" >> .env.prod
          echo "VITE_KAKAO_RESTAPI_KEY=${{ secrets.VITE_KAKAO_RESTAPI_KEY }}" >> .env.prod
          echo "VITE_REDIRECT_URI=${{ secrets.VITE_REDIRECT_URI }}" >> .env.prod

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Copy build files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          source: dist
          target: ${{ secrets.REMOTE_REPO_PATH }}

      - name: remote ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            exec bash -l
            cd ${{ secrets.REMOTE_REPO_PATH }}
            git checkout main
            git pull origin main
            pm2 restart yarn
